# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WebAPISample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.0'
  pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"

  # Pods for WebAPISample

end
